### ISSUE TITLE
0210-05 任务：slabs reassign automove 功能

### ISSUE THREAD

**Issue by yanjunli** [MyCATApache/Mycat-JCache#14]
可能涉及到的类:
高仿版 hashtable 实现入口类  io.mycat.jcache.hash.impl.AssocImpl
slabs 内存池入口类. io.mycat.jcache.memory.DefaultSlabsImpl

**Comment by newboy2004** [comment]
入参类还没有完善，review代码没问题之后再接入

**Comment by newboy2004** [comment]
已经接入
